"""
Vancouver Zoning and Development Bylaw 3575 parameters.

Complete zone parameter table covering all priority zone types. Values serve as
defaults — open data spatial overlays and property tax records override these
per-parcel when available.

Priority zones (housing policy focused):
  RS-1  Single-family residential
  RT-1  Two-family residential
  RT-3  Townhouse residential
  RM-4  Multiple dwelling (4-storey apartments)
  RM-5  West End multiple dwelling (tower forms)
  C-2   General commercial
  CD-1  Comprehensive development (site-specific)

Vancouver-specific notes:
  - Floor space ratio = FSR (same concept as FSI)
  - Bylaw uses metres throughout
  - Angular planes specified as angle from vertical (not from setback)
  - Director of Planning may vary most regulations (discretionary power)
  - Social housing bonus: up to FSR 3.0 in many zones
  - Minimum first storey height: 4.5 m (similar to Toronto CR/CRE)

Sources: Vancouver Zoning and Development Bylaw 3575, May 2026 consolidation
  District schedules extracted from PDF and hand-coded.

Verified zones (from PDF text extraction):
  RT-1, RT-2, RT-3, RT-5, RT-7, RT-8, RT-9, RT-10, RT-11
  RM-1, RM-2, RM-3, RM-4, RM-5, RM-6, RM-9A, RM-10, RM-11, RM-12, R4-1
"""

ZONE_PARAMS: dict[str, dict] = {
    # ── Residential Single-Family ──────────────────────────────────────────
    # Note: RS schedules not extracted — single-family, not missing-middle priority
    "RS-1": {
        "description": "Single Detached House",
        "max_fsr": 0.60,
        "max_fsr_social_housing": 0.75,
        "max_height_m": 9.1,
        "min_site_area_sqm": 167.0,
        "setbacks": {
            "front_m": 6.1,
            "rear_m": 7.6,
            "side_m": 1.2,
            "flanking_m": 3.0,
        },
        "angular_planes": {},
        "lot_coverage_max": 0.45,
        "bylaw_references": {
            "general": "RS-1 District Schedule",
            "fsr": "2.1.1",
            "height": "2.2.1",
            "setbacks": "2.2",
        },
    },
    "RS-2": {
        "_note": "Subclass of RS-1 — placeholder, inherits RS-1 values",
        "inherits": "RS-1",
    },
    # ── Residential Two-Family ───────────────────────────────────────────
    "RT-1": {
        "description": "Two-family (side-by-side duplex) district",
        "max_fsr": 0.60,
        "max_height_m": 6.1,
        "min_site_area_sqm": {
            "duplex": 780.0,
            "single_detached_house": 445.0,
        },
        "setbacks": {
            "front_m": 7.3,
            "rear_m": 10.7,
            "side_m": 1.5,
            "side_m_pct": 0.10,
            "flanking_m": 3.0,
        },
        "rear_yard_lane_reduction": True,
        "angular_planes": {},
        "lot_coverage_max": 0.45,
        "bylaw_references": {
            "general": "RT-1 District Schedule",
            "fsr": "3.1.1.1",
            "height": "3.1.2.2",
            "setbacks": "3.1.2.3-3.1.2.5",
            "lot_coverage": "3.1.2.6",
        },
    },
    "RT-2": {
        "description": "Two-family (front-to-back duplex) district",
        "max_fsr": {"multiple_dwelling": 0.75, "duplex": 0.60, "all_other": 0.60},
        "max_height_m": 9.2,
        "min_site_area_sqm": {"multiple_dwelling": 668.0, "duplex": 445.0},
        "setbacks": {
            "front_m": 7.3,
            "rear_m": 10.7,
            "side_m": 1.5,
            "side_m_pct": 0.10,
            "flanking_m": 3.0,
        },
        "rear_yard_lane_reduction": True,
        "angular_planes": {},
        "lot_coverage_max": {"multiple_dwelling": 0.40, "duplex": 0.45},
        "bylaw_references": {"general": "RT-2 District Schedule"},
    },
    "RT-3": {
        "description": "Townhouse district",
        "max_fsr": 0.60,
        "max_fsr_infill": 0.95,
        "max_fsr_with_bonus": 0.75,
        "max_height_m": 10.7,
        "min_site_area_sqm": {
            "multiple_dwelling": 510.0,
            "duplex": 260.0,
            "single_detached_house": 260.0,
            "infill": 418.0,
            "rooming_house": 510.0,
            "hospital": 1850.0,
        },
        "setbacks": {
            "front_m": "average_adjacent",
            "front_max_m": 3.7,
            "rear_m": 20.0,
            "side_m": 1.5,
            "side_m_pct": 0.10,
            "flanking_m": 3.0,
        },
        "rear_yard_lane_reduction": True,
        "angular_planes": {},
        "lot_coverage_max": 0.45,
        "lot_coverage_max_infill": 0.50,
        "bylaw_references": {"general": "RT-3 District Schedule"},
    },
    "RT-5": {
        "description": "Character house retention district — multiplexes on small lots",
        "max_fsr": {"no_character_house": 0.60, "director_bonus": 0.75},
        "max_height_m": {"front_building": 10.7, "rear_building": 7.7},
        "min_site_area_sqm": 338.0,
        "setbacks": {
            "front_m": 7.3,
            "rear_m": "conditional",
            "rear_m_pct": 0.30,
            "rear_m_min": 10.7,
            "side_m": 1.5,
            "side_m_pct": 0.10,
            "flanking_m": 3.0,
        },
        "rear_yard_lane_reduction": True,
        "angular_planes": {},
        "lot_coverage_max": 0.45,
        "bylaw_references": {"general": "RT-5 District Schedule"},
    },
    "RT-7": {
        "description": "Rowhouse / courtyard townhouses — 3-8 units",
        "max_fsr": {"lt_317m2": 1.00, "ge_317m2": 0.70, "rental_bonus": 1.00, "character_house": 0.70},
        "max_height_m": {"rear_building": 8.5, "other": 11.5},
        "min_site_area_sqm": {"3_units": "not_required", "4_6_units": 280.0, "7_8_units": 557.0},
        "setbacks": {
            "front_m": 4.9,
            "rear_m_courtyard": 0.9,
            "rear_m_other": 10.7,
            "side_m": 1.2,
            "flanking_m": 3.0,
        },
        "angular_planes": {},
        "lot_coverage_max": None,
        "bylaw_references": {"general": "RT-7 District Schedule"},
    },
    "RT-8": {
        "description": "Duplex / infill district — character retention focus",
        "max_fsr": 0.50,
        "max_fsr_dwelling_bonus": 0.75,
        "max_fsr_all_other": 0.60,
        "max_height_m": {"principal": 10.7, "infill": 7.7},
        "min_site_area_sqm": {"duplex": 306.0, "single_detached_house": 306.0, "multiple_conversion_dwelling": 306.0},
        "setbacks": {
            "front_m": "average_adjacent",
            "side_m": 1.5,
            "side_m_pct": 0.10,
            "flanking_m": 3.0,
        },
        "rear_yard_lane_reduction": True,
        "angular_planes": {},
        "lot_coverage_max": 0.45,
        "bylaw_references": {"general": "RT-8 District Schedule"},
    },
    "RT-9": {
        "description": "Rowhouse / courtyard townhouses — character retention variant",
        "max_fsr": {"lt_317m2": 1.00, "ge_317m2": 0.70, "rental_bonus": 1.00, "character_house": 0.70},
        "max_height_m": {"rear_building": 8.5, "other": 11.5},
        "min_site_area_sqm": {"3_units": "not_required", "4_6_units": 280.0, "7_8_units": 557.0},
        "setbacks": {
            "front_m": 4.9,
            "rear_m_courtyard": 0.9,
            "rear_m_other": 10.7,
            "side_m": 1.2,
            "flanking_m": 3.0,
        },
        "angular_planes": {},
        "lot_coverage_max": None,
        "bylaw_references": {"general": "RT-9 District Schedule"},
    },
    "RT-10": {
        "description": "Small-scale multiplex — 2-3 units per lot",
        "max_fsr": 0.40,
        "max_fsr_bonus": 0.80,
        "max_height_m": {"front_60pct": 10.7, "rear_40pct": 7.7},
        "min_site_area_sqm": {"duplex": 306.0, "single_detached_house": 306.0, "multiple_conversion_dwelling": 306.0, "infill": 306.0},
        "setbacks": {
            "front_m": "conditional",
            "side_m": 1.2,
            "side_m_pct": 0.10,
            "flanking_m": 3.0,
        },
        "angular_planes": {},
        "lot_coverage_max": 0.45,
        "bylaw_references": {"general": "RT-10 District Schedule"},
    },
    "RT-11": {
        "description": "Duplex / infill district — smaller lots than RT-8",
        "max_fsr": {"duplex": 0.75, "all_other": 0.60},
        "max_fsr_bonus": 0.90,
        "max_height_m": {"duplex_front": 10.7, "other_front": 10.7, "other_rear": 7.7},
        "min_site_area_sqm": {"duplex": 303.0, "duplex_with_suite": 334.0, "mcd_2unit": 303.0, "mcd_3unit": 334.0, "infill": 334.0},
        "setbacks": {
            "front_m": "conditional",
            "side_m": 1.2,
            "flanking_m": 3.0,
        },
        "angular_planes": {},
        "lot_coverage_max": 0.45,
        "bylaw_references": {"general": "RT-11 District Schedule"},
    },
    # ── Residential Multiple Dwelling (Apartments) ──────────────────────────
    "RM-1": {
        "description": "Courtyard townhouse / low-rise apartment district",
        "max_fsr": {"default": 0.40, "director_bonus": 1.20},
        "max_height_m": 10.7,
        "min_site_area_sqm": {"multiple_dwelling": 604.0, "duplex": 306.0, "single_detached_house": 306.0},
        "setbacks": {
            "front_m": 3.1,
            "rear_m": 0.6,
            "side_m": 1.5,
            "side_m_pct": 0.10,
            "flanking_m": 3.0,
        },
        "angular_planes": {},
        "lot_coverage_max": 0.55,
        "bylaw_references": {"general": "RM-1 District Schedule"},
    },
    "RM-2": {
        "description": "3-storey apartment / multiple dwelling district",
        "max_fsr": {"default": 0.75, "coverage_bonus": "0.009 per 1% below 50% coverage", "size_bonus": "0.0015 per 9.3m2 over 837m2", "parking_bonus": 0.15},
        "max_height_m": 10.7,
        "min_site_area_sqm": {"multiple_dwelling": 550.0, "duplex": "not_required"},
        "setbacks": {
            "front_m": 6.1,
            "rear_m": 10.7,
            "side_m": 2.1,
            "flanking_m": 3.0,
        },
        "angular_planes": {},
        "lot_coverage_max": None,
        "bylaw_references": {"general": "RM-2 District Schedule"},
    },
    "RM-3": {
        "description": "High-rise apartment district",
        "max_fsr": {"default": 1.00, "coverage_bonus": "0.012 per 1% below 50% coverage", "size_bonus": "0.002 per 9.3m2 over 837m2", "parking_bonus": 0.20},
        "max_height_m": 36.6,
        "min_site_area_sqm": {"multiple_dwelling": 550.0, "duplex": "not_required"},
        "setbacks": {
            "front_m": 6.1,
            "rear_m": 10.7,
            "side_m": 2.1,
            "flanking_m": 3.0,
        },
        "angular_planes": {},
        "lot_coverage_max": None,
        "bylaw_references": {"general": "RM-3 District Schedule"},
    },
    "RM-4": {
        "description": "Multiple dwelling (4-storey apartments, social housing)",
        "max_fsr": 0.75,
        "max_fsr_social_housing": 3.00,
        "max_fsr_director_bonus": 1.45,
        "max_height_m": 10.7,
        "max_height_social_housing_m": 19.9,
        "min_site_area_sqm": 550.0,
        "min_site_area_sqm_reduced": 500.0,
        "max_site_frontage_m": 45.8,
        "setbacks": {
            "front_m": 6.1,
            "rear_m": 10.7,
            "side_m": 2.1,
            "side_m_pct": 0.10,
            "side_m_wide": 1.5,
            "flanking_m": 3.0,
            "corner_exterior_side_pct": 0.20,
        },
        "rear_yard_lane_reduction": True,
        "angular_planes": {
            "type": "from_vertical",
            "start_height_m": 7.3,
            "angle_deg": 120,
            "angle_from_horizontal_deg": 60,
            "orientation": "north_northeast_northwest_property_line",
        },
        "lot_coverage_max": 0.65,
        "bylaw_references": {"general": "RM-4 District Schedule"},
        "use_specific": {
            "multiple_dwelling": {"max_fsr": 0.75, "max_height_m": 10.7, "min_site_area_sqm": 550.0, "max_site_frontage_m": 45.8},
            "duplex_single_detached": {"max_fsr": 0.60, "max_height_m": 10.7},
            "infill": {"max_fsr": 0.75, "max_height_m": 10.7},
            "seniors_supportive": {"max_fsr": 0.75, "max_height_m": 10.7, "min_site_area_sqm": 550.0},
            "rooming_house": {"max_fsr": 0.75, "max_height_m": 10.7, "min_site_area_sqm": 550.0},
        },
    },
    "RM-5": {
        "description": "West End multiple dwelling (towers)",
        "max_fsr": 1.00,
        "max_fsr_bonus": 1.50,
        "max_fsr_rm5a_rm5c_rm5d": 2.20,
        "max_fsr_rm5b": 2.75,
        "max_fsr_social_housing": 2.75,
        "max_height_m": 18.3,
        "max_height_bonus_m": 58.0,
        "min_site_area_sqm": 167.0,
        "setbacks": {
            "front_m": 3.7,
            "rear_m": 2.1,
            "side_m": 2.1,
            "flanking_m": 3.0,
        },
        "angular_planes": {},
        "lot_coverage_max": 0.65,
        "bylaw_references": {"general": "RM-5 District Schedule"},
    },
    "RM-5A": {"inherits": "RM-5"},
    "RM-5B": {"inherits": "RM-5"},
    "RM-5C": {"inherits": "RM-5"},
    "RM-5D": {"inherits": "RM-5"},
    "RM-6": {
        "description": "West End mixed-use (Georgia/Alberni corridor)",
        "max_fsr": {"default": 1.00, "director_bonus": 2.00},
        "max_height_m": {"west_cardero": 47.3, "east_bidwell": 41.2, "east_denman": 35.2, "west_denman": 29.0, "east_chilco": 23.0},
        "min_site_area_sqm": {"west_cardero": 604.0, "east_bidwell": 372.0, "east_denman": 279.0, "west_denman": 279.0, "east_chilco": 186.0},
        "setbacks": {
            "front_m": {"west_cardero": 7.6, "east_bidwell": 3.7, "east_denman": 3.7, "west_denman": 6.1, "east_chilco": 3.0},
            "rear_m": 3.7,
            "side_m": 1.5,
            "flanking_m": 3.0,
        },
        "angular_planes": {},
        "lot_coverage_max": None,
        "bylaw_references": {"general": "RM-6 District Schedule"},
    },
    "RM-9A": {
        "description": "4-storey apartment + townhouse district (Kitsilano)",
        "max_fsr": {"default": 0.70, "rental_15_2m": 1.50, "rental_27_4m": 2.00, "amenity_bonus": "1m2 per share"},
        "max_height_m": {"apartment": 13.7, "townhouse": 10.7},
        "min_site_area_sqm": 445.0,
        "min_site_frontage_m": 15.2,
        "max_site_frontage_m": 50.0,
        "setbacks": {
            "front_m": 3.7,
            "rear_m_apartment": 3.7,
            "rear_m_townhouse": 1.2,
            "side_m": 2.1,
            "flanking_m": 3.0,
        },
        "angular_planes": {},
        "lot_coverage_max": 0.55,
        "bylaw_references": {"general": "RM-9A District Schedule"},
    },
    "RM-10": {
        "description": "6-storey rental apartment district (Broadway corridor)",
        "max_fsr": {"default": 0.90, "rental_30m_855m2": 2.40, "rental_40m_1115m2": 2.60, "locked_in_lots": 2.00, "amenity_bonus": "1m2 per share"},
        "max_height_m": 20.0,
        "min_site_area_sqm": 855.0,
        "min_site_frontage_m": 30.0,
        "max_site_frontage_m": 50.0,
        "setbacks": {
            "front_m": 3.7,
            "rear_m_shallow": 3.7,
            "rear_m_deep": 6.1,
            "side_m": 3.0,
            "flanking_m": 3.0,
        },
        "angular_planes": {},
        "lot_coverage_max": 0.50,
        "bylaw_references": {"general": "RM-10 District Schedule"},
    },
    "RM-11": {
        "description": "4-storey apartment / mixed-use district (East Van)",
        "max_fsr": {"default": 0.75, "rental_36_6m": 1.70, "amenity_bonus": "1m2 per share"},
        "max_height_m": 13.7,
        "min_site_area_sqm": 1000.0,
        "min_site_frontage_m": 36.6,
        "max_site_frontage_m": 50.0,
        "setbacks": {
            "front_m": 3.7,
            "rear_m": 6.1,
            "side_m": 2.1,
            "flanking_m": 3.0,
        },
        "angular_planes": {},
        "lot_coverage_max": 0.55,
        "bylaw_references": {"general": "RM-11 District Schedule"},
    },
    "RM-12": {
        "description": "4-storey mixed-use residential district",
        "max_fsr": {"default": 0.75, "rental_36_6m": 1.70, "amenity_bonus": "1m2 per share"},
        "max_height_m": {"apartment": 13.7, "mixed_use": 13.7, "rear_building": 9.5},
        "min_site_area_sqm": 1000.0,
        "min_site_frontage_m": 36.6,
        "setbacks": {
            "front_m": 3.7,
            "rear_m": 6.1,
            "side_m": 2.1,
            "flanking_m": 3.0,
        },
        "angular_planes": {},
        "lot_coverage_max": 0.55,
        "bylaw_references": {"general": "RM-12 District Schedule"},
    },
    "R4-1": {
        "description": 'Mid-rise apartment and mixed-use (Cambie corridor)',
        "max_fsr": {'mid_rise_apartment': 4.0, 'mid_rise_mixed_use': 4.3, 'other': 1.45},
        "max_height_m": {'mid_rise': 47.0, 'other': 11.5},
        "min_site_area_sqm": {'corner': 1348.0, 'other': 1532.0},
        "min_site_frontage_m": {'corner': 40.0, 'other': 45.7},
        "max_site_frontage_m": 60.7,
        "setbacks": {'front_m': {'mid_rise': 3.7, 'other': 3.7}, 'rear_m': {'mid_rise': 6.1, 'other': 3.1}, 'side_m': {'mid_rise': 3.7, 'other': 1.2}, 'flanking_m': None},
        "angular_planes": {},
        "lot_coverage_max": None,
        "bylaw_references": {'general': 'R4 District Schedule'},
    },
    # ── Commercial ──────────────────────────────────────────────────────────
    "C-2": {
        "description": "General commercial district — dual regime (rental tenure mixed-use vs. all other uses)",
        "max_fsr": 0.75,
        "max_height_m": 15.3,
        "min_first_storey_height_m": 4.5,
        "setbacks": {
            "front_m": 2.5,
            "rear_m": 1.5,
            "side_m": 0.9,
            "flanking_m": 2.5,
        },
        "dual_regime": True,
        "regimes": {
            "rental_tenure_mixed_use": {
                "applicability": {
                    "outside_sub_area_a": True,
                    "min_dwelling_units": 3,
                    "min_2br_pct": 0.35,
                    "non_stratified_rental": True,
                    "third_storey_plus_dwelling_only": True,
                },
                "fsr": {
                    "base": 3.50,
                    "corner_bonus": 3.70,
                    "corner_bonus_conditions": {
                        "is_corner_lot": True,
                        "min_frontage_m": 45.7,
                        "min_lot_area_sqm": 1672.0,
                    },
                    "exterior_circulation_bonus": 0.05,
                },
                "height": {
                    "first_storey_ge_5_2m_m": 22.0,
                    "first_storey_lt_5_2m_m": 19.8,
                    "max_storeys": 6,
                    "rear_proximity_limit_m": 6.1,
                    "rear_proximity_distance_m": 4.6,
                },
                "setbacks": {
                    "front_m": 2.5,
                    "rear_dwelling_m": 4.6,
                    "rear_non_dwelling_below_6_1m_m": 1.5,
                    "rear_non_dwelling_above_6_1m_m": 4.6,
                    "rear_adjoins_r_no_lane_m": 3.1,
                    "rear_corner_lot_reduced_m": 1.5,
                    "side_adjoins_r_below_4th_m": 3.7,
                    "side_adjoins_r_at_above_4th_m": 10.7,
                    "side_no_r_m": 0.9,
                    "flanking_m": 2.5,
                },
            },
            "all_other_uses": {
                "fsr": {
                    "base": 0.75,
                    "director_bonus_multiple_dwelling": 2.15,
                    "director_bonus_all_uses": 2.50,
                    "director_bonus_condition": "first_storey_non_dwelling_ge_0_35_fsr",
                },
                "height": {
                    "first_storey_ge_5_2m_m": 15.3,
                    "first_storey_lt_5_2m_m": 13.8,
                    "rear_proximity_limit_m": 6.1,
                    "rear_proximity_distance_m": 6.1,
                },
                "setbacks": {
                    "front_m": 2.5,
                    "rear_non_dwelling_m": 1.5,
                    "rear_dwelling_m": 6.1,
                    "rear_adjoins_r_no_lane_m": 3.1,
                    "side_adjoins_r_below_4th_m": 3.7,
                    "side_adjoins_r_at_above_4th_m": 10.7,
                    "side_no_r_m": 0.9,
                    "flanking_m": 2.5,
                },
            },
        },
        "angular_planes": {
            "type": "from_vertical",
            "start_height_m": 15.3,
            "angle_deg": 135,
            "angle_from_horizontal_deg": 45,
            "exemptions": [
                {"condition": "north_south_street_24_4m_plus", "description": "Frontage on N-S street with ROW >= 24.4 m"},
                {"condition": "wide_street_27_5m_plus", "description": "Frontage on any street with ROW > 27.5 m"},
            ],
        },
        "lot_coverage_max": 1.00,
        "bylaw_references": {
            "general": "C-2 District Schedule",
            "rental_tenure": "Section 3.1",
            "other_uses": "Section 3.2",
            "fsr": "3.1.1.1 / 3.2.1.1",
            "height": "3.1.2.1 / 3.2.2.1",
            "setbacks": "3.1.2.2-3.1.2.6 / 3.2.2.2-3.2.2.4",
            "angular_planes": "3.1.2.7",
        },
    },
    "C-1": {"inherits": "C-2"},
    "C-2A": {"inherits": "C-2"},
    "C-2B": {"inherits": "C-2"},
    "C-2C": {"inherits": "C-2"},
    "C-3A": {"inherits": "C-2"},
    # ── Industrial ─────────────────────────────────────────────────────────
    "I-1": {
        "description": "Light industrial",
        "max_fsr": 1.00,
        "max_height_m": 18.3,
        "setbacks": {
            "front_m": 4.6,
            "rear_m": 4.6,
            "side_m": 3.0,
            "flanking_m": 3.0,
        },
        "angular_planes": {},
        "lot_coverage_max": 0.75,
        "bylaw_references": {"general": "I-1 District Schedule"},
    },
    "I-2": {"inherits": "I-1"},
    "I-3": {"inherits": "I-1"},
    # ── Comprehensive Development ───────────────────────────────────────────
    "CD-1": {
        "description": "Comprehensive development (site-specific)",
        "max_fsr": None,
        "max_height_m": None,
        "setbacks": {
            "front_m": None,
            "rear_m": None,
            "side_m": None,
            "flanking_m": None,
        },
        "angular_planes": {},
        "lot_coverage_max": None,
        "bylaw_references": {
            "general": "CD-1 District Schedule",
            "note": "Site-specific — no generic values",
        },
    },
    "CD": {"inherits": "CD-1"},

    "FC-1": {
        "description": 'High-density mixed commercial district (False Creek / South Main)',
        "max_fsr": {'overall': 5.0, 'dwelling': 3.0, 'hotel': 4.0, 'office': 1.5, 'retail_service': 1.0, 'other_non_dwelling': {'default': 3.0, 'with_hotel_ge_1_00': 4.0}, 'director_bonus_max': 11.0},
        "max_height_m": 69.2,
        "max_height_bonus_m": 100.0,
        "min_site_frontage_m": {'fsr_gt_5_50': 15.0},
        "max_site_frontage_m": 45.7,
        "max_unit_frontage_ground_level_m": 15.3,
        "setbacks": {'front_m': {'west_main_south_terminal': 3.0, 'south_terminal_main_to_quebec': 6.0}, 'rear_m': None, 'side_m': None, 'flanking_m': None},
        "angular_planes": {},
        "lot_coverage_max": None,
        "bylaw_references": {'general': 'FC-1 District Schedule', 'fsr': '3.1.1.2', 'height': '3.1.2.4', 'setbacks': '3.1.2.5'},
    },

    "FC-2": {
        "description": 'False Creek Flats Innovation Hub — mixed-use employment district',
        "max_fsr": {'sub_area_a': {'overall': 7.0, 'office': 6.75, 'hotel': 4.0, 'retail_service': 1.0, 'other': 3.0}, 'sub_area_b': {'non_dwelling': 5.0, 'dwelling': 3.0, 'director_bonus_max': 6.5}, 'sub_area_c1': {'non_dwelling': 1.0, 'director_bonus_max': 2.5}, 'sub_area_c2': {'overall': 4.0, 'dwelling_social_housing': 3.0, 'non_dwelling': 1.0, 'director_bonus_max': 6.5}, 'sub_area_d': {'overall': 3.0, 'director_bonus_max': 7.5}, 'sub_area_e': {'overall': 3.0, 'artist_manufacturing_etc': 3.0, 'creative_products': 1.0, 'other': 1.0}},
        "max_height_m": {'sub_area_a_b': 22.9, 'sub_area_c1': 10.7, 'sub_area_c2_d': 10.7, 'sub_area_e': 18.3},
        "max_height_bonus_m": {'sub_area_a_b': 51.8, 'sub_area_c1': 18.3, 'sub_area_c2_d': 51.8, 'sub_area_e': 42.7},
        "min_first_floor_to_floor_height_m": 6.0,
        "setbacks": {'front_m': 0.6, 'front_parking_setback_m': 1.2, 'rear_m': 0.6, 'side_m': 'not_permitted', 'side_m_corner': 0.6},
        "angular_planes": {},
        "lot_coverage_max": None,
        "bylaw_references": {'general': 'FC-2 District Schedule', 'fsr': '3.1.1, 3.2.1, 3.3.1, 3.4.1', 'height': '3.1.2.1, 3.2.2.1, 3.3.2.1, 3.4.2.1', 'setbacks': '3.1.2.2-3.1.2.4, 3.2.2.2-3.2.2.4, 3.3.2.2-3.3.2.4, 3.4.2.2-3.4.2.4'},
    },

    "FM-1": {
        "description": 'Fairview Slopes mixed residential with compatible commercial and light industrial',
        "max_fsr": {'default': 0.6, 'existing_pre_1973_dwelling_max': 1.0, 'director_bonus_max': 1.5},
        "max_height_m": 10.7,
        "max_height_south_property_line_m": 7.6,
        "setbacks": {'front_m': None, 'rear_m': None, 'side_m': None, 'flanking_m': None},
        "angular_planes": {},
        "lot_coverage_max": None,
        "bylaw_references": {'general': 'FM-1 District Schedule', 'fsr': '3.1.1.1', 'height': '3.1.2.1'},
    },

    "HA-2": {
        "description": 'Gastown Historic Area — turn of the century historical and architectural character',
        "max_fsr": None,
        "max_height_m": {'min': 12.2, 'max': 22.9},
        "min_site_area_sqm": None,
        "setbacks": {'front_m': None, 'rear_m': None, 'side_m': None, 'flanking_m': None},
        "angular_planes": {},
        "lot_coverage_max": None,
        "bylaw_references": {'general': 'HA-2 District Schedule', 'fsr': '3.1.1.1', 'height': '3.1.2.1–3.1.2.2', 'setbacks': '3.1.2'},
        "heritage_form_character": "Maintain Gastown's 'turn of the century' historical and architectural character. All alterations to exterior treatment or appearance require Director of Planning approval after consultation with any Council-approved advisory group. Outright approval retail/restaurant uses limited to ground floor only (no basement), max 500 m² GFA, max 10.7 m frontage.",
    },

    "HA-3": {
        "description": 'Yaletown Historic Area — warehouse district conversion/renovation, circa 1900 architectural features',
        "max_fsr": {'all_uses': 5.0, 'dwelling_uses': 3.0, 'non_dwelling_min': 1.5},
        "max_height_m": {'default': 21.4, 'existing_june_1986': 'height_existing_on_june_10_1986'},
        "min_site_area_sqm": None,
        "setbacks": {'front_m': 'not_permitted', 'rear_m': 'not_permitted', 'side_m': 'not_permitted', 'flanking_m': None},
        "angular_planes": {},
        "lot_coverage_max": None,
        "bylaw_references": {'general': 'HA-3 District Schedule', 'fsr': '3.1.1.1', 'height': '3.1.2.1', 'setbacks': '3.1.2.2–3.1.2.4'},
        "heritage_form_character": 'External design regulations (Section 4.3) require: masonry exterior finishes (excluding tile/concrete block), 1 natural earth-tone or white main colour, lower 4 storeys built to property line with upper storeys terraced back, wood-frame or compatible-profile windows with consistent repetitive elements replicating circa 1900 patterns, flat roofs (shallow-pitched permitted), recessed balconies, accentuated main entrances (awnings/planters/lighting), and retention/provision of decorative architectural elements (window/door decoration, parapets, cornices). Mechanical equipment must be enclosed and setback from street view. New windows on additions/renovations must replicate existing windows; new construction must replicate windows of a Heritage Register building.',
    },

    "I-1A": {
        "description": 'Light industrial district with digital entertainment/ICT focus (Quebec St / 2nd–5th Ave)',
        "max_fsr": {'industrial_uses': 3.0, 'all_other_uses': 1.0, 'all_other_bonus_max': 1.0, 'amenity_affordable_housing_bonus_max': 2.0},
        "max_height_m": 33.5,
        "min_site_area_sqm": None,
        "setbacks": {'front_m': {'quebec_street': 1.5, '2nd_avenue_south_side': '31.70_upper_floor_setback', '3rd_avenue': 0.65, '4th_avenue': 0.65, '5th_avenue': 0.65}, 'rear_m': {'north_south_lane_2nd_to_5th': 3.0, 'east_west_lane': 0.6}, 'side_m': None, 'flanking_m': None},
        "upper_floor_setbacks_m": {'quebec_street': {'ground': 1.5, 'upper_floor': 6.1, 'height_limit': 18.3}, '2nd_3rd_4th_5th_avenue': {'ground': 0.65, 'upper_floor': 4.5, 'height_limit': 18.3}, 'north_south_lane_2nd_to_5th': {'ground': 3.0, 'upper_floor': 9.1, 'height_limit': 18.3}},
        "upper_floor_area_reduction_above_18_3m": 'max_65pct_of_largest_lower_storey',
        "first_floor_to_floor_height_min_m": 5.35,
        "angular_planes": {},
        "lot_coverage_max": None,
        "bylaw_references": {'general': 'I-1A District Schedule', 'fsr': '3.1.1.1–3.1.1.2', 'height': '3.1.2.1–3.1.2.7', 'setbacks': '3.1.2.2, 3.1.2.4, 3.1.2.6'},
    },

    "I-1B": {
        "description": 'Light industrial district with digital entertainment/ICT focus (Quebec St / 5th–6th Ave)',
        "max_fsr": {'industrial_uses': 3.0, 'all_other_uses': 1.0, 'all_other_bonus_max': 1.0, 'amenity_affordable_housing_level_1_bonus_max': 2.0, 'amenity_affordable_housing_level_2_bonus_max': 1.0},
        "max_height_m": 38.0,
        "min_site_area_sqm": None,
        "setbacks": {'front_m': {'quebec_street': 1.5, '5th_avenue': 0.65, '6th_avenue': 0.65}, 'rear_m': {'north_south_lane_5th_to_6th': 3.0, 'east_west_lane': 0.6}, 'side_m': None, 'flanking_m': None},
        "upper_floor_setbacks_m": {'quebec_street': {'ground': 1.5, 'upper_floor': 6.1, 'height_limit': 18.3}, '5th_6th_avenue': {'ground': 0.65, 'upper_floor': 4.5, 'height_limit': 18.3}, 'north_south_lane_5th_to_6th': {'ground': 3.0, 'upper_floor': 9.1, 'height_limit': 18.3}},
        "upper_floor_area_reduction_above_18_3m": 'max_65pct_of_largest_lower_storey',
        "first_floor_to_floor_height_min_m": 5.35,
        "angular_planes": {},
        "lot_coverage_max": None,
        "bylaw_references": {'general': 'I-1B District Schedule', 'fsr': '3.1.1.1–3.1.1.3', 'height': '3.1.2.1–3.1.2.6', 'setbacks': '3.1.2.2, 3.1.2.4, 3.1.2.6'},
    },

    "I-1C": {
        "description": 'Employment-intensive light industrial district — transition between residential, commercial and light industrial (Mount Pleasant)',
        "max_fsr": {'industrial_uses': 6.0, 'all_other_uses': 4.0, 'industrial_floor_area_min_pct': 33.3},
        "max_height_m": {'default': 46.5, 'rooftop_amenity_max': 50.3},
        "min_site_area_sqm": None,
        "setbacks": {'front_m': {'north_south_street': 1.5, '3rd_avenue': 0.65, '4th_avenue': 0.65}, 'rear_m': {'lane': 0.6}, 'side_m': None, 'flanking_m': None},
        "upper_floor_setbacks_m": {'north_south_street': {'ground': 1.5, 'upper_floor': 6.1, 'height_limit': 21.0}, '2nd_3rd_4th_avenue': {'ground': 0.65, 'upper_floor': 4.5, 'height_limit': 21.0}},
        "first_floor_to_floor_height_min_m": 6.1,
        "second_floor_to_floor_height_min_m": 5.35,
        "angular_planes": {},
        "lot_coverage_max": None,
        "bylaw_references": {'general': 'I-1C District Schedule', 'fsr': '3.1.1.1', 'height': '3.1.2.1, 3.1.2.4, 3.1.2.6', 'setbacks': '3.1.2.2'},
    },

    "I-4": {
        "description": 'Railtown Historic Industrial District — light industrial, historic building retention encouraged',
        "max_fsr": {'manufacturing_transportation_wholesale_artist_studio_b': 5.0, 'production_rehearsal_studio_office_all_other': 2.5, 'production_rehearsal_studio_office_all_other_existing': 3.0, 'office_and_all_other_combined': 1.0, 'office_and_all_other_combined_existing': 1.5, 'office_max_pct_gfa': 25.0, 'office_max_pct_gfa_existing': 33.3, 'retail_max_m2': 500.0, 'restaurant_class_1_max_m2': 150.0},
        "max_height_m": 30.5,
        "min_site_area_sqm": None,
        "setbacks": {'front_m': None, 'rear_m': {'default': 3.1, 'lane_reduction': 'decreased_by_distance_to_lane_centre_line'}, 'side_m': None, 'flanking_m': None},
        "rear_yard_director_waiver": True,
        "angular_planes": {},
        "lot_coverage_max": None,
        "bylaw_references": {'general': 'I-4 District Schedule', 'fsr': '3.1.1.1', 'height': '3.1.2.1', 'setbacks': '3.1.2.2–3.1.2.4'},
    },

    "IC-1": {
        "description": 'Industrial Commercial district — Main Street building continuity and light industrial focus',
        "max_fsr": {'manufacturing_transportation_wholesale_class_a': 3.0, 'all_other_uses': 1.0, 'office_ancillary_to_manufacturing_max': 1.5, 'retail_max_m2': 1000.0},
        "max_height_m": {'default': 18.3, 'main_street_street_line': 12.2},
        "min_site_area_sqm": None,
        "setbacks": {'front_m': None, 'rear_m': {'default': 3.1, 'lane_reduction': 'decreased_by_distance_to_lane_centre_line'}, 'side_m': {'adjoining_r_district_no_lane': 1.5, 'not_adjoining_r_district': 'not_required', 'if_provided_min': 0.9}, 'flanking_m': None},
        "rear_yard_director_waiver": True,
        "angular_planes": {'main_street': {'type': 'from_vertical', 'start_height_m': 12.2, 'angle_deg': 135, 'angle_from_horizontal_deg': 45, 'orientation': 'street_property_line'}},
        "lot_coverage_max": None,
        "bylaw_references": {'general': 'IC-1 District Schedule', 'fsr': '3.1.1.1', 'height': '3.1.2.1, 3.1.2.4', 'setbacks': '3.1.2.2–3.1.2.7'},
    },

    "IC-2": {
        "description": 'Industrial Commercial district — Burrard Street / Fir Street / 1st–5th Ave area',
        "max_fsr": {'manufacturing_transportation_wholesale_artist_studio_b': 3.0, 'all_other_uses': 2.5, 'amenity_affordable_housing_bonus_max': 1.5, 'artist_studio_b_agreement_bonus_max': 0.5},
        "max_height_m": {'default': 30.5, 'burrard_street_line': 18.3},
        "min_site_area_sqm": None,
        "setbacks": {'front_m': {'1st_ave_pine_fir_north_of_4th_or_south_of_lane_4th_5th': 0.65, '3rd_ave_east_of_fir': 1.5, 'burrard_fir_north_of_lane_4th_5th_and_south_of_4th_or_5th_east_of_fir': 2.5, 'all_other': 'not_required'}, 'rear_m': {'default': 3.1, 'lane_reduction': 'decreased_by_distance_to_lane_centre_line'}, 'side_m': {'pine_fir_north_of_4th_or_south_of_lane_4th_5th': 0.65, 'burrard_fir_north_of_lane_4th_5th_and_south_of_4th': 2.5, 'adjoining_r_district_no_lane': 1.5, 'all_other': 'not_required', 'if_provided_min': 0.9}, 'flanking_m': None},
        "rear_yard_director_waiver": True,
        "upper_floor_setbacks_m": {'burrard_street': {'upper_floor': 6.1, 'height_limit': 18.3}},
        "angular_planes": {'burrard_street': {'type': 'from_vertical', 'start_height_m': 18.3, 'angle_deg': 135, 'angle_from_horizontal_deg': 45, 'orientation': 'street_property_line'}},
        "lot_coverage_max": None,
        "bylaw_references": {'general': 'IC-2 District Schedule', 'fsr': '3.1.1.1–3.1.1.4', 'height': '3.1.2.1, 3.1.2.5', 'setbacks': '3.1.2.2–3.1.2.4, 3.1.2.7–3.1.2.11'},
    },

    "IC-3": {
        "description": 'Industrial Commercial district — False Creek Flats (sub-area A allows mixed-use residential height/density bonuses)',
        "max_fsr": {'artist_studio_manufacturing_retail_school_theatre_transportation_wholesale_a': 3.0, 'artist_studio_with_residential_unit': 2.5, 'all_other_uses': 1.0, 'retail_max_m2': 1000.0, 'sub_area_a_mixed_use_residential_max': 4.0, 'sub_area_a_dwelling_max': 3.5},
        "max_height_m": {'default': 18.3, 'sub_area_a_mixed_use_residential_max': 30.5},
        "min_site_area_sqm": None,
        "setbacks": {'front_m': None, 'rear_m': {'default': 3.1, 'lane_reduction': 'decreased_by_distance_to_lane_centre_line'}, 'side_m': {'adjoining_r_district_no_lane': 1.5, 'not_adjoining_r_district': 'not_required', 'if_provided_min': 0.9}, 'flanking_m': None},
        "rear_yard_director_waiver": True,
        "mixed_use_residential_first_storey_dwelling_restriction_m": 10.7,
        "angular_planes": {},
        "lot_coverage_max": None,
        "bylaw_references": {'general': 'IC-3 District Schedule', 'fsr': '3.1.1.1–3.1.1.3', 'height': '3.1.2.1, 3.1.2.4', 'setbacks': '3.1.2.2–3.1.2.7'},
    },

    "M-1": {
        "description": 'Light industrial district',
        "max_fsr": {'manufacturing_transportation_wholesaling_a': 5.0, 'other': 1.0},
        "max_fsr_retail_max_sqm": 1000.0,
        "max_fsr_general_office_note": 'greater of 235 m2 or 25% of total GFA',
        "max_height_m": 30.5,
        "setbacks": {'front_m': None, 'rear_m': 3.1, 'rear_yard_lane_reduction': True, 'side_m': {'adjoins_rm_no_lane': 1.5, 'adjoins_r1_rt_ra_no_lane': 0.9, 'other': 'not_required'}, 'side_m_provided_not_required': 0.9, 'corner_exterior_side_not_required': True, 'flanking_m': None},
        "angular_planes": {},
        "lot_coverage_max": None,
        "bylaw_references": {'general': 'M-1 District Schedule', 'fsr': '3.1.1.1', 'height': '3.1.2.1', 'setbacks': '3.1.2.2-3.1.2.3'},
    },

    "M-1A": {
        "description": 'Light industrial district with residential compatibility focus',
        "max_fsr": 5.0,
        "max_fsr_retail_max_sqm": 1000.0,
        "max_height_m": 18.3,
        "setbacks": {'front_m': {'adjoins_r_district': 3.0, 'other': 'not_required'}, 'rear_m': 3.1, 'rear_yard_lane_reduction': True, 'side_m': {'adjoins_rm_no_lane': 1.5, 'adjoins_ra_r1_rt_no_lane': 0.9, 'other': 'not_required'}, 'side_m_provided_not_required': 0.9, 'corner_exterior_side_not_required': True, 'flanking_m': None},
        "angular_planes": {},
        "lot_coverage_max": None,
        "bylaw_references": {'general': 'M-1A District Schedule', 'fsr': '3.1.1.1', 'height': '3.1.2.1', 'setbacks': '3.1.2.2-3.1.2.4'},
    },

    "M-1B": {
        "description": 'Light industrial district with restricted non-industrial uses',
        "max_fsr": {'default': 1.5, 'director_bonus_max': 2.0},
        "max_fsr_retail_max_sqm": 1000.0,
        "max_fsr_general_office_note": 'greater of 235 m2 or 25% of total GFA',
        "min_site_area_sqm": 6000.0,
        "max_height_m": 12.2,
        "setbacks": {'front_m': None, 'rear_m': 3.1, 'rear_yard_lane_reduction': True, 'side_m': {'major_street_landscaped': '10% of site frontage', 'adjoins_r_district_no_lane': '10% of site frontage', 'other': 'not_required'}, 'side_m_limits_m': {'min': 1.5, 'max': 6.1}, 'flanking_m': None},
        "angular_planes": {},
        "lot_coverage_max": None,
        "bylaw_references": {'general': 'M-1B District Schedule', 'fsr': '3.1.1.1', 'height': '3.1.2.2', 'setbacks': '3.1.2.3-3.1.2.4'},
    },

    "M-2": {
        "description": 'Heavy industrial district',
        "max_fsr": {'manufacturing_transportation_wholesaling_a': 5.0, 'other': 1.0},
        "max_fsr_retail_max_sqm": 1000.0,
        "max_fsr_retail_convenience_gas_max_sqm": 200.0,
        "max_fsr_general_office_note": 'greater of 235 m2 or 25% of total GFA',
        "max_fsr_restaurant_class_1_max_sqm": 300.0,
        "max_fsr_brewing_distilling_lounge_max_sqm": {'inside': 80.0, 'outside': 80.0},
        "max_height_m": 30.5,
        "setbacks": {'front_m': None, 'rear_m': 3.1, 'rear_yard_lane_reduction': True, 'side_m': {'adjoins_rm_no_lane': 1.5, 'adjoins_r1_rt_ra_no_lane': 0.9, 'other': 'not_required'}, 'side_m_provided_not_required': 0.9, 'corner_exterior_side_not_required': True, 'flanking_m': None},
        "angular_planes": {},
        "lot_coverage_max": None,
        "bylaw_references": {'general': 'M-2 District Schedule', 'fsr': '3.1.1.1', 'height': '3.1.2.1', 'setbacks': '3.1.2.2-3.1.2.3'},
    },

    "RA-1": {
        "description": 'Semi-rural / equestrian / limited agricultural district',
        "max_fsr": {'dwelling_community_care_group': 'greater of 0.10 or 334 m2, max 836 m2', 'other': 0.12},
        "max_height_m": 9.2,
        "min_site_area_sqm": 9100.0,
        "setbacks": {'front_m': 7.3, 'rear_m': 4.5, 'side_m': 4.5, 'flanking_m': None},
        "angular_planes": {'type': 'from_vertical', 'start_height_m': 6.4, 'angle_deg': 135, 'angle_from_horizontal_deg': 45, 'orientation': 'side_property_line'},
        "lot_coverage_max": {'dwelling_community_care_group': 'greater of 8% or 242 m2', 'other': '12% of site area'},
        "bylaw_references": {'general': 'RA-1 District Schedule'},
    },

    "RM-3A": {
        "description": 'Multiple dwelling (3-storey apartments, social housing)',
        "max_fsr": {'default': 1.0, 'coverage_bonus': '0.012 per 1% below 50% coverage', 'size_bonus': '0.002 per 9.3m2 over 837m2', 'parking_bonus': 0.2, 'social_housing_bonus': 3.0, 'duplex_single_detached': 0.6},
        "max_height_m": 10.7,
        "max_height_social_housing_m": 19.9,
        "min_site_area_sqm": {'default': 550.0, 'reduced': 500.0},
        "setbacks": {'front_m': 6.1, 'rear_m': 10.7, 'side_m': 2.1, 'flanking_m': None, 'corner_exterior_side_pct': 0.2, 'corner_exterior_side_min_m': 3.0, 'corner_exterior_side_max_m': 6.0},
        "rear_yard_lane_reduction": True,
        "angular_planes": {},
        "lot_coverage_max": None,
        "bylaw_references": {'general': 'RM-3A District Schedule'},
        "use_specific": {'multiple_dwelling': {'max_fsr': 1.0, 'max_height_m': 10.7, 'min_site_area_sqm': 550.0}, 'duplex_single_detached': {'max_fsr': 0.6, 'max_height_m': 10.7, 'min_site_area_sqm': 550.0}, 'seniors_supportive': {'max_fsr': 1.0, 'max_height_m': 10.7, 'min_site_area_sqm': 550.0}, 'rooming_house': {'max_fsr': 1.0, 'max_height_m': 10.7, 'min_site_area_sqm': 550.0}},
    },

    "RR-1": {
        "description": 'Rental tenure townhouse and triplex district',
        "max_fsr": {'townhouse_4storey_gt8_units': 1.45, 'townhouse_3storey_gt8_units': 1.2, 'townhouse_5_to_8_units': 1.0, 'townhouse_4_units_or_triplex': 1.0},
        "max_height_m": {'townhouse_4storey_front': '13.7 m and 4 storeys', 'other_front': '11.5 m and 3 storeys', 'rear_building': '10.7 m and 3 storeys'},
        "min_site_area_sqm": {'townhouse_4storey_gt8_units': 920.0, 'townhouse_3storey_gt8_units': 613.0, 'townhouse_5_to_8_units': 465.0, 'townhouse_4_units_or_triplex': 303.0},
        "max_site_area_sqm": {'townhouse_gt8_units': 1500.0},
        "min_site_frontage_m": {'townhouse_4storey_gt8_units': 30.1, 'townhouse_3storey_gt8_units': 20.1, 'townhouse_5_to_8_units': 15.2, 'townhouse_4_units_or_triplex': 10.0},
        "max_site_frontage_m": {'townhouse_gt8_units': 40.2},
        "setbacks": {'front_m': 3.7, 'rear_m': 3.1, 'side_m': 1.2, 'flanking_m': None},
        "angular_planes": {},
        "lot_coverage_max": None,
        "bylaw_references": {'general': 'RR-1 District Schedule'},
    },

}

# ── Resolve inheritance ───────────────────────────────────────────────

def _resolve_inheritance(params: dict) -> dict:
    """Deep-copy parent values then overlay child overrides."""
    inherits = params.pop("inherits", None)
    if inherits:
        import copy
        resolved = copy.deepcopy(ZONE_PARAMS[inherits])
        resolved.update(params)
        return resolved
    return params


for code in list(ZONE_PARAMS.keys()):
    ZONE_PARAMS[code] = _resolve_inheritance(dict(ZONE_PARAMS[code]))
